project_name: assimilis

builds:
  - binary: assimilis
    main: ./cmd/assimilis/

    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/traefik/assimilis/pkg/version.Version={{ .Version }}
      - -X github.com/traefik/assimilis/pkg/version.Commit={{ .Commit }}
      - -X github.com/traefik/assimilis/pkg/version.Date={{ .Date }}

    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: assimilis
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
